name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    environment: development
    runs-on: ubuntu-latest
    env:
      CI: ${{ vars.CI }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Public Frontend
      run: |
        echo "--- Starting build"
        ./tools/build.sh
        echo "--- Ending build"
    - uses: actions/upload-artifact@master
      with:
        name: frontend-public
        path: ./public
  test:
    name: Test
    environment: development
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/download-artifact@master
      with:
        name: frontend-public
        path: ./public
  deploy:
    name: Deploy
    environment: development
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: frontend-public
          path: ./public
      - name: Deploy to Digital Ocean
        run: echo "--- Starting Deployment"
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.0
        with:
          remote_host:  ${{ secrets.DIGITAL_OCEAN_PUBLIC_IP }}
          remote_user: ${{ secrets.DIGITAL_OCEAN_USER_NAME }}
          remote_key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
          remote_path: /app
          switches: -avzr --delete
          path: /
      - name: executing remote deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_PUBLIC_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER_NAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
          port: 22
          script:
            echo "$(pwd)"
            echo "$(ls)"
            echo "$(ls /app)"
            /app/serve.sh
      - name: Deploy to Digital Ocean
        run: echo "--- Ending Deployment"